name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --target test --tag todo-app:test
    - run: docker run --env-file ./.env.test todo-app:test



  dockerpublish:
    name: Docker Hub
    runs-on: ubuntu-latest
    needs: build
    
    if: github.ref_name == 'main'
    steps:
    - run: echo "Publishing!" 
    - uses: actions/checkout@v2
    
    - name: docker build
      run: docker build -t miraclemag1c/module_8 .

    - name: dockerhublogin
      run: echo ${{secrets.DOCKER_HUB_TOKEN}} | docker login --username miraclemag1c --password-stdin

    - name: push
      run: docker push miraclemag1c/todo-app-module_8

  heroku:
    runs-on: ubuntu-latest
    needs: dockerpublish
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "ian-davenport-module-8"
          heroku_email: "ian.davenport@kpmg.co.uk"
          usedocker: true
